USE mysql;
-- UPDATE user SET authentication_string=PASSWORD('YOURPASSWORD') WHERE User='root';
-- UPDATE user SET PASSWORD=PASSWORD('YOURPASSWORD') WHERE User='root';
SET PASSWORD FOR 'root' = PASSWORD("YOURPASSWORD");
FLUSH PRIVILEGES;